#!/bin/bash
set -e -u -o pipefail
[ -f "$GHR_PATH" ] && cd -- "$(dirname -- "$GHR_PATH")" && export GHR_PATH="$(basename -- "$GHR_PATH")"
[ -d "$GHR_PATH" ] && cd -- "$GHR_PATH" && export GHR_PATH=.
[ -n "${GHR_COMPRESS:-}" ] && eval "$(/usr/local/bin/ghr-compress)"
export GHR_REV=$(git -C ${GHR_PATH} rev-parse --short HEAD)
/usr/local/bin/ghr -u "${GITHUB_REPOSITORY%/*}" -r "${GITHUB_REPOSITORY#*/}" "release-${GHR_REV}" "$GHR_PATH"
